name: Check Apache License

on:
  push

jobs:
  ubuntu-build:
    name: check license
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         repository: ${{github.repository}}
         ref: ${{ env.BRANCH_NAME }}

     - name: Check License Header
       uses: apache/skywalking-eyes/header@main
