name: Check Apache License

on:
  push

jobs:
  ubuntu-build:
    name: check license
    runs-on: ubuntu-latest
    steps:
      - name: Check License Header
        uses: apache/skywalking-eyes/header@main
        with:
          config: licenserc.yaml
