name: LOC

on:
  push
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         repository: ${{github.repository}}
         ref: ${{ env.BRANCH_NAME }}

     - name: NPM Init
       uses: ./third_party/loc_script/ # Uses an action in the root directory
       run: npm init -y 

     - name: NPM Install
       uses: ./third_party/loc_script/ # Uses an action in the root directory
       run: npm install 

     - name: Launch the local action
       id: badge
       uses: ./third_party/loc_script/ # Uses an action in the root directory
       with:
         debug: true
         directory: ./
         patterns: '**/*.h|**/*.cpp'
         badge: ./output/badge.svg
         ignore: 'node_modules/|README'

     - name: Deploy to image-data branch
       uses: peaceiris/actions-gh-pages@v3
       with:
         publish_dir: ./output
         publish_branch: image-data
         github_token: ${{ secrets.GITHUB_TOKEN }}
         user_name: 'github-actions[bot]'
         user_email: 'github-actions[bot]@users.noreply.github.com'

