name: Unite Test 

on: [push] 

jobs:
  ubuntu-build:
    name: build
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Cache protobuf library
         id: cache-protobuf
         uses: actions/cache@v1
         with:
           path: protobuf
           key: ${{ runner.os }}-protobuf
      - name: Init environment 
         run: |
           git clone https://github.com/protocolbuffers/protobuf.git
           cd protobuf
           git submodule update --init --recursive
           ./autogen.sh
           ./autogen.sh
           ./configure
           make
           make check
           sudo make install
           sudo ldconfig      

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
            version: "3.19.4"

      - uses: actions/checkout@v1
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel
      - name: build
        run: bazel test ...

      - name: Collect Test Coverage File
        if: always()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: coverage-output
          path: "/home/runner/.cache/bazel/_bazel_runner/be4defad2350bee802e807363d03d888/execroot/_main/bazel-out/k8-fastbuild/testlogs/interface/common/resdb_txn_accessor_test/"
