name: Unite Test 

on: [push] 

jobs:
  ubuntu-build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel
      - name: build
        run: bazel test ...

      - name: Collect Test Coverage File
        if: always()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: coverage-output
          path: "/home/runner/.cache/bazel/_bazel_runner/be4defad2350bee802e807363d03d888"
